name: "Setup Terraform"
description: "Sets up Terraform CLI in your GitHub Actions workflow, given version in .terraform-version."

runs:
  using: "composite"
  steps:
    - name: Read required Terraform CLI version
      id: terraform-version
      shell: bash
      run: |
        set -eu
        echo "version=$(cat .terraform-version)" >> $GITHUB_OUTPUT
    - name: Install Terraform CLI
      # Third-party action, pin to commit SHA!
      # See https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions
      uses: hashicorp/setup-terraform@97f030cf6dc0b4f5e0da352c7bca9cca34579800
      with:
        terraform_version: ${{ steps.terraform-version.outputs.version }}
        terraform_wrapper: false
